export global Skin := {
        property<brush>   background :     #000;
        property<brush>   dark :           #3A3C49;
        property<brush>   darkshadow :     #2C2F38;
        property<brush>   medium :         #4e505c;
        property<brush>   edge :           #4e505c;
        property<brush>   light:           #fff;
    }

export MenuBar :=

    Rectangle{

        property <string> title;

        height:30px;
        VerticalLayout{   
        width:parent.width;
        height:parent.height; 

        Text {

            text: root.title;
            font-size:12px;
            color: white;
            horizontal-alignment:center;
            vertical-alignment:center;
        }
    }
}

export CustomButton :=

    Rectangle{
    callback clicked();
    property <string> text;


       width:100px;
       height:30px;
       border-radius:15px;

       VerticalLayout {  

           Text{
            text:root.text;
            color:white;
            horizontal-alignment: center;
            vertical-alignment: center;
           }
        }

       TouchArea {  
       clicked => {root.clicked()}
        }
}