import { ScrollView, Button, CheckBox, SpinBox, Slider, GroupBox, LineEdit, StandardListView,
    ComboBox, HorizontalBox, VerticalBox, GridBox, TabWidget, TextEdit, AboutSlint } from "std-widgets.slint";

import {TrainSystem, Track, Section} from "train_systems.slint";
import {Skin, MenuBar, CustomButton} from "components.slint";

import "./fonts/Avenir_85_Heavy.ttf";


    MainWindow := Window {

        title:"Train Simulator";
        background: Skin.background;
        default-font-size:24px;
        default-font-family:"Avenir Heavy";
        min-width:700px;
        min-height:700px;
        preferred-width:700px;
        preferred-height:700px;

        //properties
        property <int> counter : 0;
        property <[Section]> sections;

        //callbacks
        callback reset();
        callback set_counter(int);

        VerticalLayout{

            spacing:2px;
            alignment:stretch;

        MenuBar{title: "Train Simulator"; background: Skin.dark;}


        Rectangle{

            background:Skin.dark;
            width: parent.width;
            height:parent.height;
            border-radius:5px;

            Rectangle{

                background:white;
                opacity:0.11;
                height:1px;
                width:parent.width;
            }

            VerticalLayout{

                width:parent.width;
                height:parent.height;
                alignment:center;
                spacing: 20px;

                Text {
                    padding:5px;
                    text: "Counter";
                    color: white;
                    font-size:14px;
                    horizontal-alignment:center;
                }

                HorizontalLayout{

                    alignment:center;

                    Rectangle{

                        border-radius:5px;
                        background: Skin.darkshadow;
                        width:75px;
                        height:75px;
                        drop-shadow-offset-y: 10px;
                        drop-shadow-color: Skin.darkshadow;
                        drop-shadow-blur:10px;


                        VerticalLayout{

                            width:parent.width;
                            height:parent.height;

                            counter-label := Text {

                                text: counter;
                                color: white;
                                horizontal-alignment:center;
                                vertical-alignment:center;
                            }
                        }
                    }
                }

                HorizontalLayout {  

                    alignment:center;

                    CustomButton{text:"reset"; background:Skin.medium;clicked => {root.reset();}}

                    CustomButton { text:"set 5"; background:Skin.medium; clicked => {root.set-counter(5);} }
                }

                Track{sections: root.sections;color: Skin.medium;}

            }
        }
    }
}
